# The following three options specify
# a madlibs-style description of yourself.
# I ____________  at ____________________.
# I like ________________________________.
# No need for periods, we'll add them :)

I: architect frontend code
at: SheKnows
I like: to create


# Add your twitter handle to display your most 
# recent tweet and link to your twitter account

Twitter: adamwdrpaer
